CREATE DATABASE  IF NOT EXISTS `crdatabase` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `crdatabase`;
DROP TABLE IF EXISTS `crtable`;
CREATE TABLE `crtable` (
  `id` varchar(50) NOT NULL,
  `value_copyrightedSymbol` text,
  `x_copyrightedSymbol` varchar(1000) DEFAULT NULL,
  `date_copyrightedSymbol` varchar(1000) DEFAULT NULL,
  `value_copyrighted` text,
  `x_copyrighted` varchar(1000) DEFAULT NULL,
  `date_copyrighted` varchar(1000) DEFAULT NULL,
  `value_copyright` text,
  `x_copyright` varchar(1000) DEFAULT NULL,
  `date_copyright` varchar(1000) DEFAULT NULL,
  `value_copr` text,
  `x_copr` varchar(1000) DEFAULT NULL,
  `date_copr` varchar(1000) DEFAULT NULL,
  `joinedcaseb_col8` text,
  `joinedcaseb_col9` text,
  `joinedcaseb_col10` text,
  `joinedcaseb_col11` text,
  `joinedcaseb_col12` text,
  `joinedcaseb_col13` text,
  `joinedcaseb_col14` text,
  `joinedcaseb_col15` text,
  `joinedcaseb_col16` text,
  `joinedcaseb_col17` text,
  `joinedcaseb_col18` text,
  `joinedcaseb_col19` text,
  `joinedcaseb_col20` text,
  `joinedcaseb_col21` text,
  `joinedcaseb_col22` text,
  `joinedcaseb_col23` text,
  `joinedcaseb_col24` text,
  `joinedcaseb_col25` text,
  `joinedcaseb_col26` text,
  `joinedcaseb_col27` text,
  `joinedcaseb_col28` text,
  `joinedcaseb_col29` text,
  `joinedcaseb_col30` text,
  `joinedcaseb_col31` text,
  `joinedcaseb_col32` text,
  `joinedcaseb_col33` text,
  `joinedcaseb_col34` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
LOAD DATA LOCAL INFILE 'D:\\YourPath\\To\\date_finder_result.txt' INTO TABLE crtable FIELDS terminated by '\t' LINES terminated by '\n' IGNORE 1 rows;
